spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379

      # Redis连接池配置
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      # Redis超时配置
      timeout: 5000ms
      # 连接超时
      connect-timeout: 5000ms
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.zk: debug
    org.springframework.data.redis: debug



