spring:
  application:
    name: springAI
  ai:
    zhipuai:
      base-url: https://open.bigmodel.cn/api/paas
      api-key:
      chat:
        options:
          model: glm-4.6

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.springai: debug
